repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b # v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
        args: ["--maxkb=1000"]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 751b8b57ba617d78eec57b4ec91753568a8a496c # v0.8.5
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 648203cec3e499b9eff54a24d6cf4b25ce02eb1e # v1.14.0
    hooks:
      - id: mypy
        additional_dependencies:
          - types-requests
          - pydantic
        args: [--no-strict-optional, --ignore-missing-imports]
